database:
  dbname: database_name_goes_here
  user: dtabase_username_goes_here
  password: database_password_goes_here
  host: database_host_goes_here
  port: database_port_goes_here

paths:
  csv_directory: /csv/directory/path/goes/here
  output_directory: /export/output/directory/goes/here
csv_settings:
  delimiter: "\t" # or "," or "|" or whatever your delimiter is
  